namespace XrmEmulator.MetadataSync.Commit;

public enum CommitItemType
{
    SavedQuery,
    SystemForm,
    SiteMap,
    Entity,
    IconUpload,
    IconSet,
    AppModuleEntity,
    AppModuleView,
    AppModuleForm,
    AppModuleBpf,
    BusinessRule,
    Delete,
    Deprecate,
    NewEntity,
    NewAttribute,
    WebResourceUpload,
    CommandBar,
    RibbonWorkbench,
    PluginRegistration,
    RelationshipUpdate,
    NewManyToManyRelationship,
    DataImport,
    AssociationsImport,
    SecurityRoleUpdate,
    SecurityRoleAssignment,
    AppModuleRole,
    WorkflowActivation,
    WorkflowRemoveFromSolution,
    PcfControl,
    OptionSetValue,
    StatusValue,
    AddSolutionComponent,
    AddDirectSolutionComponent,
    EnableChangeTracking,
    CustomApiRegistration,
    SlaItem,
    SlaKpi,
    RelationshipDelete,
    EntityMetadataDelete,
    EnvironmentVariable,
    SecurityRoleDelete,
    SecurityRolePrivilegeRemove,
    PluginManagedIdentity,
    PluginContentUpdate
}

public record CommitItem(CommitItemType Type, string DisplayName, string FilePath, object ParsedData);
